### ISSUE TITLE
Create a form to record a food delivery 

### ISSUE THREAD

**Issue by dvidsilva** [TechForPR/chefsForPR#21]
Look for the fields in #20  and wait for that to be closed.

For the design, use a standard bootstrap form design, create a similar static method in the model like the one in `models/Request.js`.

It will use the endpoint `POST /api/delivery/` and send the form data. Verify it stores correctly by looking into the database or by requesting `/api/delivery/:shortId` using the short id returned when creating the delivery

**Comment by dvidsilva** [comment]
@slay2k Would you be able to work on this? is super similar to the other forms and is only needed in english.

**Comment by slay2k** [comment]
@dvidsilva Sorry bud, saw this late, looks like you got it done!
