### ISSUE TITLE
Create a form to request food (HTML/CSS/JS) English

### ISSUE THREAD

**Issue by dvidsilva** [TechForPR/chefsForPR#5]
Look for the fields in #3 , wait for #4  to close before starting work on this one

For the design, use a standard bootstrap form design

It will use the endpoint `/api/request/new` and send the form data. Verify it stores correctly by looking into the database or by requesting `/api/request/status/:shortId` using the short id returned when creating the request.

**Comment by abermudez** [comment]
Working on this one. Please add me as collaborator.

**Comment by slay2k** [comment]
Can do this one. Please add me as collaborator @dvidsilva

**Comment by slay2k** [comment]
Ready to push changes, awaiting access.

**Comment by dvidsilva** [comment]
@slay2k  sent you an invite so you can push and open a pull request

**Comment by dvidsilva** [comment]
Thanks @slay2k !
